name: Deploy site

on: 
  push:
    branches:
      - main
    paths:
      - 'src/**'

  workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        environment: 
          name: prod
        steps:
            - uses: actions/checkout@v2
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ap-southeast-2


            - name: Deploy to S3
              run: make upload_site
              env:
                TF_VAR_website_domain_main: ${{ secrets.TF_VAR_website_domain_main }}